### ISSUE TITLE
`ort::error::Error` is no longer `Send + Sync` in `2.0.0-rc.12` due to `SessionBuilder`

### ISSUE THREAD

**Issue by DOCtorActoAntohich** [pykeio/ort#550]
## minimal example

the following dependencies are enough

```toml
[dependencies]
anyhow = "1"
ort = "=2.0.0-rc.12"
```

the following code should reproduce the issue

```rust
fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
    let session = Session::builder()?
        .with_intra_threads(n_threads)?
        .commit_from_file(model)?;
    Ok(session)
}
```

## problem description

the above code previously worked on `2.0.0-rc.10` and `2.0.0-rc.11`, but causes a compilation error on `2.0.0-rc.12`

note that `.with_intra_threads(...)` method is not the only one at fault - all the `with_xxx` methods that return `BuilderResult` cause the same issue.

<details>
  <summary>[click to see the full error log]</summary>

```txt
error[E0277]: `?` couldn't convert the error: `NonNull<OrtSessionOptions>: Sync` is not satisfied
   --> src/main.rs:13:39
    |
 11 | fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
    |                                                                 ----------------------- required `NonNull<OrtSessionOptions>: Sync` because of this
 12 |     let session = Session::builder()?
 13 |         .with_intra_threads(n_threads)?
    |          -----------------------------^ `NonNull<OrtSessionOptions>` cannot be shared between threads safely
    |          |
    |          this can't be annotated with `?` because it has type `Result<_, ort::Error<SessionBuilder>>`
    |
    = help: within `builder::SessionOptionsPointer`, the trait `Sync` is not implemented for `NonNull<OrtSessionOptions>`
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
note: required because it appears within the type `builder::SessionOptionsPointer`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:251:19
    |
251 | pub(crate) struct SessionOptionsPointer(NonNull<ort_sys::OrtSessionOptions>);
    |                   ^^^^^^^^^^^^^^^^^^^^^
    = note: required for `Arc<builder::SessionOptionsPointer>` to implement `Send`
note: required because it appears within the type `SessionBuilder`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:71:12
    |
 71 | pub struct SessionBuilder {
    |            ^^^^^^^^^^^^^^
note: required because it appears within the type `ort::Error<SessionBuilder>`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/error.rs:75:12
    |
 75 | pub struct Error<R = ()> {
    |            ^^^^^
    = note: required for `anyhow::Error` to implement `From<ort::Error<SessionBuilder>>`

error[E0277]: `?` couldn't convert the error: `NonNull<OrtSessionOptions>: Send` is not satisfied
   --> src/main.rs:13:39
    |
 11 | fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
    |                                                                 ----------------------- required `NonNull<OrtSessionOptions>: Send` because of this
 12 |     let session = Session::builder()?
 13 |         .with_intra_threads(n_threads)?
    |          -----------------------------^ `NonNull<OrtSessionOptions>` cannot be sent between threads safely
    |          |
    |          this can't be annotated with `?` because it has type `Result<_, ort::Error<SessionBuilder>>`
    |
    = help: within `builder::SessionOptionsPointer`, the trait `Send` is not implemented for `NonNull<OrtSessionOptions>`
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
note: required because it appears within the type `builder::SessionOptionsPointer`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:251:19
    |
251 | pub(crate) struct SessionOptionsPointer(NonNull<ort_sys::OrtSessionOptions>);
    |                   ^^^^^^^^^^^^^^^^^^^^^
    = note: required for `Arc<builder::SessionOptionsPointer>` to implement `Send`
note: required because it appears within the type `SessionBuilder`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:71:12
    |
 71 | pub struct SessionBuilder {
    |            ^^^^^^^^^^^^^^
note: required because it appears within the type `ort::Error<SessionBuilder>`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/error.rs:75:12
    |
 75 | pub struct Error<R = ()> {
    |            ^^^^^
    = note: required for `anyhow::Error` to implement `From<ort::Error<SessionBuilder>>`

error[E0277]: `?` couldn't convert the error: `(dyn std::any::Any + 'static): Sync` is not satisfied
  --> src/main.rs:13:39
   |
11 | fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
   |                                                                 ----------------------- required `(dyn std::any::Any + 'static): Sync` because of this
12 |     let session = Session::builder()?
13 |         .with_intra_threads(n_threads)?
   |          -----------------------------^ `(dyn std::any::Any + 'static)` cannot be shared between threads safely
   |          |
   |          this can't be annotated with `?` because it has type `Result<_, ort::Error<SessionBuilder>>`
   |
   = help: the trait `Sync` is not implemented for `(dyn std::any::Any + 'static)`
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = note: required for `Arc<(dyn std::any::Any + 'static)>` to implement `Send`
note: required because it appears within the type `Option<Arc<(dyn std::any::Any + 'static)>>`
  --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/core/src/option.rs:600:10
note: required because it appears within the type `SessionBuilder`
  --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:71:12
   |
71 | pub struct SessionBuilder {
   |            ^^^^^^^^^^^^^^
note: required because it appears within the type `ort::Error<SessionBuilder>`
  --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/error.rs:75:12
   |
75 | pub struct Error<R = ()> {
   |            ^^^^^
   = note: required for `anyhow::Error` to implement `From<ort::Error<SessionBuilder>>`

error[E0277]: `?` couldn't convert the error: `(dyn std::any::Any + 'static): Send` is not satisfied
  --> src/main.rs:13:39
   |
11 | fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
   |                                                                 ----------------------- required `(dyn std::any::Any + 'static): Send` because of this
12 |     let session = Session::builder()?
13 |         .with_intra_threads(n_threads)?
   |          -----------------------------^ `(dyn std::any::Any + 'static)` cannot be sent between threads safely
   |          |
   |          this can't be annotated with `?` because it has type `Result<_, ort::Error<SessionBuilder>>`
   |
   = help: the trait `Send` is not implemented for `(dyn std::any::Any + 'static)`
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = note: required for `Arc<(dyn std::any::Any + 'static)>` to implement `Send`
note: required because it appears within the type `Option<Arc<(dyn std::any::Any + 'static)>>`
  --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/core/src/option.rs:600:10
note: required because it appears within the type `SessionBuilder`
  --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:71:12
   |
71 | pub struct SessionBuilder {
   |            ^^^^^^^^^^^^^^
note: required because it appears within the type `ort::Error<SessionBuilder>`
  --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/error.rs:75:12
   |
75 | pub struct Error<R = ()> {
   |            ^^^^^
   = note: required for `anyhow::Error` to implement `From<ort::Error<SessionBuilder>>`

error[E0277]: `?` couldn't convert the error: `NonNull<OrtMemoryInfo>: Sync` is not satisfied
   --> src/main.rs:13:39
    |
 11 | fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
    |                                                                 ----------------------- required `NonNull<OrtMemoryInfo>: Sync` because of this
 12 |     let session = Session::builder()?
 13 |         .with_intra_threads(n_threads)?
    |          -----------------------------^ `NonNull<OrtMemoryInfo>` cannot be shared between threads safely
    |          |
    |          this can't be annotated with `?` because it has type `Result<_, ort::Error<SessionBuilder>>`
    |
    = help: within `MemoryInfo`, the trait `Sync` is not implemented for `NonNull<OrtMemoryInfo>`
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
note: required because it appears within the type `MemoryInfo`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/memory.rs:376:12
    |
376 | pub struct MemoryInfo {
    |            ^^^^^^^^^^
    = note: required for `Arc<MemoryInfo>` to implement `Send`
note: required because it appears within the type `Option<Arc<MemoryInfo>>`
   --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/core/src/option.rs:600:10
note: required because it appears within the type `SessionBuilder`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:71:12
    |
 71 | pub struct SessionBuilder {
    |            ^^^^^^^^^^^^^^
note: required because it appears within the type `ort::Error<SessionBuilder>`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/error.rs:75:12
    |
 75 | pub struct Error<R = ()> {
    |            ^^^^^
    = note: required for `anyhow::Error` to implement `From<ort::Error<SessionBuilder>>`

error[E0277]: `?` couldn't convert the error: `NonNull<OrtMemoryInfo>: Send` is not satisfied
   --> src/main.rs:13:39
    |
 11 | fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
    |                                                                 ----------------------- required `NonNull<OrtMemoryInfo>: Send` because of this
 12 |     let session = Session::builder()?
 13 |         .with_intra_threads(n_threads)?
    |          -----------------------------^ `NonNull<OrtMemoryInfo>` cannot be sent between threads safely
    |          |
    |          this can't be annotated with `?` because it has type `Result<_, ort::Error<SessionBuilder>>`
    |
    = help: within `MemoryInfo`, the trait `Send` is not implemented for `NonNull<OrtMemoryInfo>`
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
note: required because it appears within the type `MemoryInfo`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/memory.rs:376:12
    |
376 | pub struct MemoryInfo {
    |            ^^^^^^^^^^
    = note: required for `Arc<MemoryInfo>` to implement `Send`
note: required because it appears within the type `Option<Arc<MemoryInfo>>`
   --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/core/src/option.rs:600:10
note: required because it appears within the type `SessionBuilder`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:71:12
    |
 71 | pub struct SessionBuilder {
    |            ^^^^^^^^^^^^^^
note: required because it appears within the type `ort::Error<SessionBuilder>`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/error.rs:75:12
    |
 75 | pub struct Error<R = ()> {
    |            ^^^^^
    = note: required for `anyhow::Error` to implement `From<ort::Error<SessionBuilder>>`

error[E0277]: `?` couldn't convert the error: `NonNull<OrtCustomOpDomain>: Sync` is not satisfied
   --> src/main.rs:13:39
    |
 11 | fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
    |                                                                 ----------------------- required `NonNull<OrtCustomOpDomain>: Sync` because of this
 12 |     let session = Session::builder()?
 13 |         .with_intra_threads(n_threads)?
    |          -----------------------------^ `NonNull<OrtCustomOpDomain>` cannot be shared between threads safely
    |          |
    |          this can't be annotated with `?` because it has type `Result<_, ort::Error<SessionBuilder>>`
    |
    = help: within `OperatorDomain`, the trait `Sync` is not implemented for `NonNull<OrtCustomOpDomain>`
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
note: required because it appears within the type `OperatorDomain`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/operator/mod.rs:122:12
    |
122 | pub struct OperatorDomain {
    |            ^^^^^^^^^^^^^^
    = note: required for `Arc<OperatorDomain>` to implement `Send`
    = note: 1 redundant requirement hidden
    = note: required for `smallvec::SmallVec<[Arc<OperatorDomain>; 1]>` to implement `Send`
note: required because it appears within the type `SessionBuilder`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:71:12
    |
 71 | pub struct SessionBuilder {
    |            ^^^^^^^^^^^^^^
note: required because it appears within the type `ort::Error<SessionBuilder>`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/error.rs:75:12
    |
 75 | pub struct Error<R = ()> {
    |            ^^^^^
    = note: required for `anyhow::Error` to implement `From<ort::Error<SessionBuilder>>`

error[E0277]: `?` couldn't convert the error: `NonNull<OrtCustomOpDomain>: Send` is not satisfied
   --> src/main.rs:13:39
    |
 11 | fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
    |                                                                 ----------------------- required `NonNull<OrtCustomOpDomain>: Send` because of this
 12 |     let session = Session::builder()?
 13 |         .with_intra_threads(n_threads)?
    |          -----------------------------^ `NonNull<OrtCustomOpDomain>` cannot be sent between threads safely
    |          |
    |          this can't be annotated with `?` because it has type `Result<_, ort::Error<SessionBuilder>>`
    |
    = help: within `OperatorDomain`, the trait `Send` is not implemented for `NonNull<OrtCustomOpDomain>`
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
note: required because it appears within the type `OperatorDomain`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/operator/mod.rs:122:12
    |
122 | pub struct OperatorDomain {
    |            ^^^^^^^^^^^^^^
    = note: required for `Arc<OperatorDomain>` to implement `Send`
    = note: 1 redundant requirement hidden
    = note: required for `smallvec::SmallVec<[Arc<OperatorDomain>; 1]>` to implement `Send`
note: required because it appears within the type `SessionBuilder`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:71:12
    |
 71 | pub struct SessionBuilder {
    |            ^^^^^^^^^^^^^^
note: required because it appears within the type `ort::Error<SessionBuilder>`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/error.rs:75:12
    |
 75 | pub struct Error<R = ()> {
    |            ^^^^^
    = note: required for `anyhow::Error` to implement `From<ort::Error<SessionBuilder>>`

error[E0277]: `?` couldn't convert the error: `(dyn Operator + 'static): Sync` is not satisfied
   --> src/main.rs:13:39
    |
 11 | fn create_session(model: impl AsRef<Path>, n_threads: usize) -> anyhow::Result<Session> {
    |                                                                 ----------------------- required `(dyn Operator + 'static): Sync` because of this
 12 |     let session = Session::builder()?
 13 |         .with_intra_threads(n_threads)?
    |          -----------------------------^ `(dyn Operator + 'static)` cannot be shared between threads safely
    |          |
    |          this can't be annotated with `?` because it has type `Result<_, ort::Error<SessionBuilder>>`
    |
    = help: the trait `Sync` is not implemented for `(dyn Operator + 'static)`
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = note: required for `Unique<(dyn Operator + 'static)>` to implement `Sync`
note: required because it appears within the type `Box<(dyn Operator + 'static)>`
   --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/alloc/src/boxed.rs:234:12
note: required because it appears within the type `operator::bound::BoundOperator`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/operator/bound.rs:12:19
    |
 12 | pub(crate) struct BoundOperator {
    |                   ^^^^^^^^^^^^^
    = note: required for `Unique<operator::bound::BoundOperator>` to implement `Sync`
note: required because it appears within the type `Box<operator::bound::BoundOperator>`
   --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/alloc/src/boxed.rs:234:12
note: required because it appears within the type `PhantomData<Box<operator::bound::BoundOperator>>`
   --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/core/src/marker.rs:819:12
note: required because it appears within the type `ort::__private::alloc::raw_vec::RawVec<Box<operator::bound::BoundOperator>>`
   --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/alloc/src/raw_vec/mod.rs:73:19
note: required because it appears within the type `Vec<Box<operator::bound::BoundOperator>>`
   --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/alloc/src/vec/mod.rs:438:12
note: required because it appears within the type `OperatorDomain`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/operator/mod.rs:122:12
    |
122 | pub struct OperatorDomain {
    |            ^^^^^^^^^^^^^^
    = note: required for `Arc<OperatorDomain>` to implement `Send`
    = note: 1 redundant requirement hidden
    = note: required for `smallvec::SmallVec<[Arc<OperatorDomain>; 1]>` to implement `Send`
note: required because it appears within the type `SessionBuilder`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/session/builder/mod.rs:71:12
    |
 71 | pub struct SessionBuilder {
    |            ^^^^^^^^^^^^^^
note: required because it appears within the type `ort::Error<SessionBuilder>`
   --> /nix/var/nix/builds/nix-21661-1756237178/cargo-vendor-dir/ort-2.0.0-rc.12/src/error.rs:75:12
    |
 75 | pub struct Error<R = ()> {
    |            ^^^^^
    = note: required for `anyhow::Error` to implement `From<ort::Error<SessionBuilder>>`

For more information about this error, try `rustc --explain E0277`.
```
</details>

i explored the source code for a little bit and concluded that in `2.0.0-rc.11` the `ort::Error` was `Send` and `Sync`, but wasn't generic over the inner value.

however, on `2.0.0-rc.12` it's no longer the case because `ort::Error<T>` can accept `SessionBuilder` that is `!Send` and `!Sync`, which in turn makes `Error<SessionBuilder>` non-send and non-sync, which is why the compilation fails.

## expected behavior

i'd prefer the crate-level `ort::Error` to implement `Send` and `Sync` 

because it gives me both flexibility and confidence 🥺

## suggestions

for the `SessionBuilder` specifically, `std::fs::OpenOptions` kind of builder (with methods taking `&mut self` instead of `self`) might be more flexible and would no longer require `Error::with_recover` because the user would own the builder fully and could still handle the error.

this consequently turns `Error<SessionBuilder>` into `Error<()>` and makes it `Send` and `Sync`

**Comment by decahedron1** [comment]
If you don't need recovery, the function definition can be made to return `ort::Result<Session>` instead of `anyhow::Result<Session>`, since `ort::Error<()>: From<ort::Error<SessionBuilder>>`, and that type is `Send` + `Sync`.
