### ISSUE TITLE
Linking failure with ort=2.0.0-rc.6 and onnxruntime=1.19.2 on Linux

### ISSUE THREAD

**Issue by ia0** [pykeio/ort#299]
Steps to reproduce:

```shell
cd /tmp
python3 -m venv venv
source venv/bin/activate
python3 -m pip install cmake
git clone --recursive https://github.com/Microsoft/onnxruntime.git
cd onnxruntime
git checkout v1.19.2
./build.sh --config=Release --parallel
cd ..
git clone https://github.com/google/magika.git
cd magika/rust/cli
ORT_LIB_LOCATION=/tmp/onnxruntime/build/Linux cargo build --release
```

Expected output: no linking error

Actual output:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: [...]
  = note: rust-lld: error: undefined symbol: absl::log_internal::LogMessage::LogMessage(char const*, int, absl::LogSeverity)
          >>> referenced by simplify.cc
          >>>               simplify.cc.o:(re2::CoalesceWalker::ShortVisit(re2::Regexp*, re2::Regexp*)) in archive /tmp/magika/rust/target/release/deps/libort_sys-c5ad07999a77da92.rlib
          >>> referenced by regexp.cc
          >>>               regexp.cc.o:(re2::NumCapturesWalker::ShortVisit(re2::Regexp*, int)) in archive /tmp/magika/rust/target/release/deps/libort_sys-c5ad07999a77da92.rlib
          >>> referenced by tostring.cc
          >>>               tostring.cc.o:(re2::ToStringWalker::~ToStringWalker()) in archive /tmp/magika/rust/target/release/deps/libort_sys-c5ad07999a77da92.rlib
          >>> referenced 87 more times
[...]
          rust-lld: error: undefined symbol: absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<unsigned long, 0>(unsigned long const&)
          >>> referenced by re2.cc
          >>>               re2.cc.o:(re2::RE2::Match(std::basic_string_view<char, std::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::basic_string_view<char, std::char_traits<char>>*, int) const (.cold)) in archive /tmp/magika/rust/target/release/deps/libort_sys-c5ad07999a77da92.rlib
          >>> referenced by re2.cc
          >>>               re2.cc.o:(re2::RE2::Match(std::basic_string_view<char, std::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::basic_string_view<char, std::char_traits<char>>*, int) const (.cold)) in archive /tmp/magika/rust/target/release/deps/libort_sys-c5ad07999a77da92.rlib
          >>> referenced by re2.cc
          >>>               re2.cc.o:(re2::RE2::Match(std::basic_string_view<char, std::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::basic_string_view<char, std::char_traits<char>>*, int) const (.cold)) in archive /tmp/magika/rust/target/release/deps/libort_sys-c5ad07999a77da92.rlib
          >>> referenced 4 more times
          collect2: error: ld returned 1 exit status
          

error: could not compile `magika-cli` (bin "magika") due to 1 previous error
```

Note that linking also fails with 1.19.0 but works with 1.18.2. However running the resulting binary fails with:

```
The requested API version [19] is not available, only API versions [1, 18] are supported in this build. Current ORT Version is: 1.18.2
thread 'main' panicked at [...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ort-2.0.0-rc.6/src/lib.rs:223:57:
Failed to initialize ORT API
```

For context, we are trying to create a manylinux binary using maturin. This means there is only glibc 2.28, which is why we build from source. ~~However, it seems even that might not be enough because I still see undefined reference to `__libc_single_threaded` in this [workflow run](https://github.com/google/magika/actions/runs/11404810115/job/31734793681?pr=747).~~ [EDIT: I was actually building ONNX Runtime outside the container...]

**Comment by decahedron1** [comment]
Could you try a [`[patch]`](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) to see if https://github.com/pykeio/ort/commit/4da570026a85e2a4a9984550e428e99f81c70b1d fixed the issue? If so, that commit will be in an rc.7 releasing today.

**Comment by ia0** [comment]
> Could you try a [`[patch]`](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) to see if [4da5700](https://github.com/pykeio/ort/commit/4da570026a85e2a4a9984550e428e99f81c70b1d) fixed the issue? If so, that commit will be in an rc.7 releasing today.

It's fixing most of the errors. The remaining ones are:

```
  = note: rust-lld: error: undefined symbol: absl::debugging_internal::VDSOSupport::VDSOSupport()
          >>> referenced by symbolize.cc
          >>>               symbolize.cc.o:(absl::debugging_internal::(anonymous namespace)::Symbolizer::GetUncachedSymbol(void const*) (.constprop.0)) in archive /tmp/magika/rust/target/release/deps/libort_sys-56c3e117cb85f6eb.rlib
          
          rust-lld: error: undefined symbol: absl::debugging_internal::VDSOSupport::LookupSymbolByAddress(void const*, absl::debugging_internal::ElfMemImage::SymbolInfo*) const
          >>> referenced by symbolize.cc
          >>>               symbolize.cc.o:(absl::debugging_internal::(anonymous namespace)::Symbolizer::GetUncachedSymbol(void const*) (.constprop.0)) in archive /tmp/magika/rust/target/release/deps/libort_sys-56c3e117cb85f6eb.rlib
          collect2: error: ld returned 1 exit status
```

However, when using the latest `main` commit b19cff4de3197f18f2f3d662349a286791359bf0 then it links correctly and runs correctly. I'll try that in the manylinux container to see if I have remaining errors there.

**Comment by ia0** [comment]
I confirm this also works when building inside a manylinux container ([example run](https://github.com/google/magika/actions/runs/11406772170)).

We can close the issue from my side. I'll just use `2.0.0-rc.7` once it's released.

**Comment by decahedron1** [comment]
[`2.0.0-rc.7`](https://crates.io/crates/ort/2.0.0-rc.7) released.
